version: '2'

services:
  memcached:
    restart: always
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  app:
    build: docker/app
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/project
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/99-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/99-custom.ini
    depends_on:
      - memcached
    env_file:
      - variables.env
