<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand" href="/">Currency Converter</a>
    </div>
</nav>
<header class="masthead text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h3 class="mb-5">Ooooops! Looks like you are lost!</h3>
                <h1>404</h1>
                <h4>Let's go to the <a href="/">Home page</a> and start once again.</h4>
            </div>
        </div>
    </div>
</header>




